### ISSUE TITLE
When Using the Auto Check Identity Updates Before Git Commands Snippet, Git Commands with Files that Contains Spaces in the Names are Broken

### ISSUE THREAD

**Issue by groomsy** [prydonius/karn#9] opened 2015-05-29 17:35 UTC
If I have `if which karn > /dev/null; then eval "$(karn init)"; fi` in my `~/.bash_profile`, anytime I  try to perform a git command on a file with a space in the name, the command fails.

**Comment by prydonius** [comment] 2015-05-29 18:27
I can't seem to reproduce on my end, can you post the error you're receiving?

**Comment by groomsy** [comment] 2015-05-29 19:00
Sure:

```
~/Developer $ mkdir test
~/Developer $ cd test
~/Developer/test $ git init
Not inside Git work tree
Initialized empty Git repository in /Users/toddgrooms/Developer/test/.git/
~/Developer/test $ touch test\ test.txt
~/Developer/test *$ git status
On branch master

Initial commit

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	test test.txt

nothing added to commit but untracked files present (use "git add" to track)
~/Developer/test *$ git add test\ test.txt
fatal: pathspec 'test' did not match any files
~/Developer/test *$ git add "test test.txt"
fatal: pathspec 'test' did not match any files
~/Developer/test *$ git add 'test test.txt'
fatal: pathspec 'test' did not match any files
```

**Comment by groomsy** [comment] 2015-05-29 19:01
Also, my `~/.bash_profile` for reference:

```
# Go
export GOPATH=$HOME/Developer/go
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOPATH/bin:$GOROOT/bin

# Karn - https://github.com/prydonius/karn
if which karn > /dev/null; then eval "$(karn init)"; fi
```

**Comment by prydonius** [comment] 2015-05-29 22:40
Thanks for the info, turns out I couldn't reproduce it in zsh, but encountered the issue in bash. I just committed a fix that worked for me, could you try checking out the latest version to see if it fixes the issue?

Thanks!

**Comment by groomsy** [comment] 2015-05-29 22:46
Absolutely. Will check out this weekend.

Thanks!

Todd Grooms
todd(dot)grooms(at)gmail(dot)com

**Comment by groomsy** [comment] 2015-05-31 15:56
Stupid problem: I've cloned the repo, checked out the commit. I have removed the old src from the `go get` command from the initial install and have placed the cloned repo there. When I run `go install`, I get nothing in the bin directory. Am I missing something here?

**Comment by groomsy** [comment] 2015-05-31 16:00
Derp. Never mind, just saw the `cmd/karn` directory.

**Comment by groomsy** [comment] 2015-05-31 16:01
This works for me! :+1: 

Thank you for the quick turnaround!

**Comment by prydonius** [comment] 2015-06-01 18:58
Great! Thanks for reporting :)

**Closed by prydonius** 2015-06-01 18:58 UTC
